(defvar home-dir (file-name-directory load-file-name)
  "The root dir of emacs configure")

(defvar setup-dir (concat home-dir "p/")
  "This directory house setup files")
(defvar vendor-dir (concat home-dir "vendor/")
  "This directory house Emacs Lisp packages that are not yet available in ELPA (or MELPA).")

(add-to-list 'load-path vendor-dir)
(let ((default-directory vendor-dir)) (normal-top-level-add-subdirs-to-load-path))
(add-to-list 'load-path setup-dir)

(require 'package-setup)
(require 'global)
(require 'appearance)
(require 'keys-binding)
(require 'tramp-setup)
(require 'ido-setup)
(require 'eshell-setup)
(require 'yasnippet-setup)
(require 've-setup)
(require 'mode-setup)
(require 'recentf-setup)
(require 'uniquify-setup)
(require 'ac)
(require 'magit-setup)
(require 'dired-setup)
(require 'erc-setup)
(require 'ack-setup)
(require 'projectile-setup)
(require 'ace-jump-setup)
(require 'mc-setup)
(require 'helm-setup)
(require 'wg-setup)
(require 'flycheck-setup)
(require 'org-setup)

(provide 'init)
;;; init.el ends here
